apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: production-1-pvc
  namespace: production-1
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
